
:concurrency: 5 # 并发数
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
- default
- [myqueue, 2]
 
development:
:concurrency: 5
staging:
:concurrency: 10
production:
:concurrency: 20